name: nestjs_ldap-backend

services:

  database:
    image: 'postgres:18-alpine'
    container_name: backend-postgres
    restart: always
    env_file: '.env'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - 'db_storage:/var/lib/postgresql/data'
      - './init-data.sh:/docker-entrypoint-initdb.d/init-data.sh'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - ldap_network

volumes:
  db_storage:
    driver: local
    name: nestjs_ldap-backend-data

networks:
  ldap_network:
    driver: bridge
    name: nestjs_ldap_network