name: nestjs_ldap-backend

services:

  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    restart: always
    env_file:
      - .env.prod
    environment:
      - HOST=0.0.0.0
      - POSTGRES_HOST=backend-postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=${CACHE_HOST}
      - REDIS_PORT=${CACHE_PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - ldap_network

  database:
    platform: linux/amd64
    image: 'postgres:18-alpine'
    container_name: backend-postgres
    restart: always
    env_file: '.env.prod'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - 'db_storage:/var/lib/postgresql/data'
      - './init-data.sh:/docker-entrypoint-initdb.d/init-data.sh'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - ldap_network

  cache:
    platform: linux/amd64
    container_name: backend-cache
    image: 'amd64/memcached:1-trixie'
    env_file: '.env.prod'
    restart: always
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    volumes:
      - 'cache_storage:/var/lib/postgresql/data'
    networks:
      - ldap_network

volumes:
  db_storage:
    driver: local
    name: nestjs_ldap-backend-data

  cache_storage:
    driver: local
    name: nestjs_ldap-backend-cache

networks:
  ldap_network:
    driver: bridge
    name: nestjs_ldap_network
